__default__:
    account: kirklandj-lab
    partition: serial
    time: 08:00:00
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log
    error: results/errors/slurm-%x.%A.%a.err

call_peaks_with_macs2:
    cpus-per-task: 4
    mem: 32G
    time: 04:00:00
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.sample}.slurm-%x.%A.%a.err

merge_bams_per_set:
    cpus-per-task: 2
    mem: 16G
    time: 06:00:00
    cores: 2
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

call_macs2_on_merged_bam:
    cpus-per-task: 4
    mem: 32G
    time: 06:00:00
    cores: 4
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

generate_consensus_peaks_by_overlap:
    cpus-per-task: 4
    mem: 32G
    time: 02:00:00
    cores: 4
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

extract_reads_for_consensus:
    cpus-per-task: 2
    mem: 16G
    time: 01:00:00
    cores: 2
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

create_bigwig_from_consensus:
    cpus-per-task: 4
    mem: 16G
    time: 02:00:00
    cores: 4
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

make_euler_plot_of_overlaps_from_beds:
    cpus-per-task: 4
    mem: 16G
    time: 02:00:00
    cores: 4
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

midpoint_and_peak_overlaps:
    cpus-per-task: 4
    mem: 16G
    time: 02:00:00
    cores: 4
    name: "{rule}.midpoints"
    output: results/logs/{rule}.midpoints.slurm-%x.%A.%a.log
    error: results/errors/{rule}.midpoints.slurm-%x.%A.%a.err

generate_heatmap:
    cpus-per-task: 8
    mem: 64G
    time: 08:00:00
    cores: 8
    name: "{rule}.heatmap"
    output: results/logs/{rule}.heatmap.slurm-%x.%A.%a.log
    error: results/errors/{rule}.heatmap.slurm-%x.%A.%a.err

euler_plot_by_mark:
    cpus-per-task: 4
    mem: 16G
    time: 02:00:00
    cores: 4
    name: "{rule}.{wildcards.mark}"
    output: results/logs/{rule}.{wildcards.mark}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.mark}.slurm-%x.%A.%a.err

generate_unique_heatmap:
    cpus-per-task: 8
    mem: 64G
    time: 08:00:00
    cores: 8
    name: "{rule}.heatmap"
    output: results/logs/{rule}.heatmap.slurm-%x.%A.%a.log
    error: results/errors/{rule}.heatmap.slurm-%x.%A.%a.err
